In [2]:
import numpy as np

In [4]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print(X)

[[  4.58137725  -2.44624596   1.61337408 ...  -6.02899704 -10.48518395
   15.32933134]
 [ 19.89706759  -3.14979115  -4.4313948  ...  22.22262401  14.31169804
    4.02189991]
 [ -5.43114027  -0.25080549  11.34186716 ...   2.49543152  16.53943594
   -7.38439303]
 ...
 [  4.35803146  12.2934635    1.53914437 ...  -3.40770543  16.34131633
  -14.62223504]
 [  1.56517508   8.87882406  -9.10893816 ...  -0.90698714   1.84037287
   11.69155678]
 [ 11.74032904  -2.69149757  -2.29983057 ...  -1.03735569  10.87638335
  -17.40531086]]


In [8]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

In [11]:
X_norm = (X - mean) /std

In [12]:
print(X_norm)

[[ 0.3398287  -0.33678486  0.09753451 ... -0.72270774 -1.13437985
   1.4772815 ]
 [ 1.858869   -0.40652239 -0.50728874 ...  2.24439615  1.32903932
   0.37362492]
 [-0.65323248 -0.11916614  1.07094124 ...  0.17256355  1.55035151
  -0.739681  ]
 ...
 [ 0.31767683  1.12425982  0.09010728 ... -0.44740869  1.53066953
  -1.4461272 ]
 [ 0.04067584  0.78579041 -0.97531109 ... -0.18477275  0.09008914
   1.1222182 ]
 [ 1.04986762 -0.36109494 -0.29401018 ... -0.1984646   0.98776173
  -1.71776802]]


In [28]:
a = np.sum(X,axis=1)
print (np.extract(a > 10,a).shape)

(715,)


In [36]:
A = np.eye(3)
B = np.eye(3)
print(np.stack((A,B),axis=0))

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]
